In [2]:
import numpy as np

In [10]:
#Array
a = np.array([1,2,3,4,5,6,7,8,9])

In [11]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a * 3 

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [13]:
a + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
z = np.zeros((2,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
o = np.ones((3,2))
o

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
r = np.arange(4,20,3)
r

array([ 4,  7, 10, 13, 16, 19])

In [17]:
l = np.linspace(0,10,6)

In [18]:
l

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [29]:
# 2 dimension array
d2 = np.array([[1,2,3], [4,5,6]])
d2

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a[4]

np.int64(5)

In [32]:
l[2]

np.float64(4.0)

In [33]:
#Slicing an array
a[1:6]

array([2, 3, 4, 5, 6])

In [34]:
a[-1]

np.int64(9)

In [35]:
a[:2]

array([1, 2])

In [36]:
a[1:-4]

array([2, 3, 4, 5])

In [37]:
a[-4:-1]

array([6, 7, 8])

In [38]:
a[-4:]

array([6, 7, 8, 9])

In [39]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [40]:
d2

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
#Slicing 2D array
d2[1,1]

np.int64(5)

In [44]:
d2[0,2]

np.int64(3)

In [45]:
d2[0, 1:]

array([2, 3])

In [46]:
d2[1, 0:2]

array([4, 5])

In [47]:
d2[: , 1:]

array([[2, 3],
       [5, 6]])

In [48]:
b = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
b[1: , 1:]

array([[5, 6],
       [8, 9]])

In [59]:
b[0:2 , :2]

array([[1, 2],
       [4, 5]])

In [63]:
b[-2:, -1:]

array([[6],
       [9]])

In [67]:
b[-3:, -3:-1]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [71]:
b[1:, -2]

array([5, 8])

In [72]:
r 

array([ 4,  7, 10, 13, 16, 19])

In [79]:
x = r.reshape((3,2))
x

array([[ 4,  7],
       [10, 13],
       [16, 19]])

In [80]:
f = r.flatten()
f

array([ 4,  7, 10, 13, 16, 19])

In [83]:
rav = r.ravel()
rav

array([ 4,  7, 10, 13, 16, 19])

In [52]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [53]:
# Arithmetic Functions
x + y

array([5, 7, 9])

In [54]:
y - x

array([3, 3, 3])

In [55]:
x * y

array([ 4, 10, 18])

In [56]:
y / x

array([4. , 2.5, 2. ])

In [57]:
y // x

array([4, 2, 2])

In [58]:
y ** x

array([  4,  25, 216])

In [59]:
# Broadcasting
x + 3

array([4, 5, 6])

In [60]:
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[10, 20, 30]])

In [61]:
a * b

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [62]:
b / a

array([[10. , 10. , 10. ],
       [ 2.5,  4. ,  5. ]])

In [63]:
a / b

array([[0.1 , 0.1 , 0.1 ],
       [0.4 , 0.25, 0.2 ]])

In [64]:
a // b

array([[0, 0, 0],
       [0, 0, 0]])

In [65]:
b // a

array([[10, 10, 10],
       [ 2,  4,  5]])

In [66]:
b ** 3 / a

array([[1000., 4000., 9000.],
       [ 250., 1600., 4500.]])

In [67]:
#Random Module
s = np.random.randint(1,3, size=(2,3))
s

array([[2, 1, 2],
       [1, 2, 1]], dtype=int32)

In [68]:
t = np.random.random((2,3))
t

array([[0.9041121 , 0.25360839, 0.0954505 ],
       [0.53448872, 0.62837234, 0.81545104]])

Aggregation Functions

In [69]:
arr = np.array([[1,2,3], [5,6,7]])

In [70]:
np.sum(arr)

np.int64(24)

In [71]:
np.mean(arr)

np.float64(4.0)

In [72]:
np.min(arr)

np.int64(1)

In [73]:
np.max(arr)

np.int64(7)

In [74]:
np.sum(arr, axis=0)

array([ 6,  8, 10])

In [75]:
np.sum(arr, axis=1)

array([ 6, 18])